-- https://www.hackerrank.com/challenges/contest-leaderboard/problem?isFullScreen=true

SELECT H.HACKER_ID, H.NAME, SUM(MAX_SCORE)
FROM (
    SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID
) S
    INNER JOIN HACKERS H ON S.HACKER_ID = H.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(MAX_SCORE) != 0
ORDER BY 3 DESC, 1;