-- https://www.hackerrank.com/challenges/full-score/problem?isFullScreen=true

SELECT H.HACKER_ID, H.NAME
FROM SUBMISSIONS S
    INNER JOIN HACKERS H ON S.HACKER_ID = H.HACKER_ID
    INNER JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
    INNER JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(*) > 1
ORDER BY COUNT(*) DESC, H.HACKER_ID;