-- https://www.hackerrank.com/challenges/the-report/problem?isFullScreen=true

SELECT A.NAME, B.GRADE, A.MARKS
FROM STUDENTS A
    INNER JOIN GRADES B
    ON A.MARKS BETWEEN B.MIN_MARK AND B.MAX_MARK
WHERE B.GRADE >= 8
ORDER BY GRADE DESC, NAME;

SELECT 'NULL' AS NAME, B.GRADE, A.MARKS
FROM STUDENTS A
    INNER JOIN GRADES B
    ON A.MARKS BETWEEN B.MIN_MARK AND B.MAX_MARK
WHERE B.GRADE < 8
ORDER BY GRADE DESC, MARKS;