-- https://www.hackerrank.com/challenges/interviews/problem?isFullScreen=true

SELECT A.CONTEST_ID, A.HACKER_ID, A.NAME, SUM(TOTAL_SUBMISSIONS), SUM(TOTAL_ACCEPTED_SUBMISSIONS), SUM(TOTAL_VIEWS), SUM(TOTAL_UNIQUE_VIEWS)
FROM CONTESTS A 
	INNER JOIN COLLEGES B ON A.CONTEST_ID = B.CONTEST_ID
    INNER JOIN CHALLENGES C ON B.COLLEGE_ID = C.COLLEGE_ID
    LEFT JOIN (
		SELECT CHALLENGE_ID, SUM(TOTAL_SUBMISSIONS) AS TOTAL_SUBMISSIONS, SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TOTAL_ACCEPTED_SUBMISSIONS
		FROM SUBMISSION_STATS 
		GROUP BY CHALLENGE_ID
	) S ON C.CHALLENGE_ID = S.CHALLENGE_ID
    LEFT JOIN (
		SELECT CHALLENGE_ID, SUM(TOTAL_VIEWS) AS TOTAL_VIEWS, SUM(TOTAL_UNIQUE_VIEWS) AS TOTAL_UNIQUE_VIEWS
		FROM VIEW_STATS 
		GROUP BY CHALLENGE_ID
    ) V ON C.CHALLENGE_ID = V.CHALLENGE_ID
GROUP BY A.CONTEST_ID, A.HACKER_ID, A.NAME
HAVING SUM(TOTAL_SUBMISSIONS) > 0
	OR SUM(TOTAL_ACCEPTED_SUBMISSIONS) > 0
    OR SUM(TOTAL_VIEWS) > 0
    OR SUM(TOTAL_UNIQUE_VIEWS) > 0
ORDER BY A.CONTEST_ID;